### ISSUE TITLE
Domain name

### ISSUE THREAD

**Issue by joecridge** [danielswaine/SodburyChallenge#19]
Can you contact whoever owns `chippingsodburyscouts.org.uk` and ask them to add an A-record pointing a subdomain like `challenge` to `178.62.20.90`?

**Comment by danielswaine** [comment]
Still hasn't updated, `Internal Server Error 500`

**Comment by joecridge** [comment]
Yeah I noticed that. It's still pointing at 79.170.44.140

**Comment by danielswaine** [comment]
Is it?? What's that address?

**Comment by joecridge** [comment]
That's the IP address for the rest of the club website (i.e. it's still being served by Apache on their server).

**Comment by danielswaine** [comment]
Hmm, maybe it hasn’t propagated yet.

**Comment by joecridge** [comment]
Has it been 48 hours?

**Comment by danielswaine** [comment]
Pretty sure it hasn't yet...

**Comment by joecridge** [comment]
No need to worry yet then :P

**Comment by joecridge** [comment]
Surely it's been 48 hours by now? XD

**Comment by danielswaine** [comment]
I know :worried: I might have to get him to contact 123-reg

**Comment by joecridge** [comment]
Yeah can you ask him?

**Comment by danielswaine** [comment]
One step ahead of you :wink:

**Comment by danielswaine** [comment]
123-Reg have said that as the hosting is not with them, you would need to login to the hosting control panel and point to IP address...

**Comment by joecridge** [comment]
Yeah, he should be able to access the hosting control panel by logging into his 123-ref account. He doesn't need to do change anything on the server.

**Comment by danielswaine** [comment]
The hosting isn't done through 123-reg, it's done through Heart Internet I'm pretty sure - I think this is the problem?

**Comment by joecridge** [comment]
Hosting won't affect DNS. If the website uses 123-reg nameservers then he needs to log into 123-reg and add an A record. If he's using Heart Internet's nameservers then he needs to find their host records panel and add an A record there.

**Comment by danielswaine** [comment]
I don't know what the problem is then because 123-Reg is pushing it onto the hosting provider...

**Comment by joecridge** [comment]
Just checked, DNS has been transferred away from 123-reg so it's not their problem.

From Heart Internet's site:
> To point a subdomain *to an IP address*:
> 
> 1. Log into your *[Domain Control Panel](http://www.managethisdomain.com/)*
> 2. Click ‘DNS Management’
> 3. Under ‘Create New A/AAAA/CNAME records’, enter in the subdomain (without the .your-domain.com attached) and the IP address it should point to
> 4. Click ‘Update DNS’
> 5. The subdomain will now point to that IP address
> 
> Due to DNS propagation, pointing your subdomain to an IP address will take approximately 24 hours to work as expected.

What he *doesn't* need to do is alter anything under Web Tools section of his eXtend Control Panel. That won't have any effect.

**Comment by danielswaine** [comment]
He doesn't have access to DNS as it's shared hosting, so just going to use my link.

**Comment by joecridge** [comment]
Ah that's lame, rule 1 of the internet is never to transfer you've domain to your host :P

**Comment by joecridge** [comment]
Can I add a credit to both of us in the site footer or something? I'm not a huge fan of the implication that you wrote the whole thing :stuck_out_tongue_closed_eyes:

**Comment by danielswaine** [comment]
I've added one :smile:
