### ISSUE TITLE
Team scoring

### ISSUE THREAD

**Issue by joecridge** [danielswaine/SodburyChallenge#2]
- Checkbox for each checkpoint on the course, tick all checkpoints visited upon return.
- Record actual finish time (needs to be entered manually since not necessarily saved straight away).
- Same for phone in time.
- Seniors have bonuses based on checkpoints visited.
- Everyone has time-based bonuses (down to minute).

**Comment by joecridge** [comment]
This is my interpretation of the scoring based on the rules:

1. Teams start with 0 points. [Implicit]
2. Teams gain the points value of every checkpoint they visit. [Implicit]
3. Teams gain additional bonuses specific to the Challenge. [Implicit]
3. Teams receive `[30 - (phone_in_time.to_i - target_phone_in_time.to_i) / 60).abs, 0].max` points for phoning in (i.e. 30 points if within 1 minute of target time, 29 if within 2 minutes, … , 1 point if within 30 minutes, 0 points otherwise). [Rule 6]
4. Teams are disqualified if they don't phone in at all. [Rule 6]
5. Teams are disqualified if they don't visit the compulsory checkpoint(s). [Rule 7]
6. Teams receive `(finish_time > target_finish_time && -[(finish_time.to_i - target_finish_time.to_i) / 60), 30].min) || 0` points. (E.g. 0 points if finish early or on time or up to 1 minute later than target time, -1 points if up to 2 minutes late, … , -29 points if up to 30 minutes late, -30 points if any later). [Rule 11]
7. Teams are disqualified if `(finish_time.to_i - target_finish_in_time.to_i) / 60) >= 30`, i.e. if finish 30 or more minutes later than target time. [Rule 11]

Is this right?

**Comment by joecridge** [comment]
Also, are the teams told what they need to do to get the bonus points?

**Comment by danielswaine** [comment]
1. Teams start with 60 as long as they phone in and finish
2. Correct
3. *Senior Section teams receive bonuses but Correct
4. 30 points for on time, 29 for 1 minute early/late, 28 for 2 minutes early/late
5. Correct
6. Correct
7. 30 points if finish on time or early, -1 for 1 minute late, -2 for two minutes late...
8. Correct

**Comment by joecridge** [comment]
1. So ignoring all checkpoint-related points, if a team phones in on time and finishes on time, they will have 120 points?
2.  
3. Yeah, that's what I meant. Each section has its own instance of the Challenge class, so a junior section just doesn't have any bonuses defined. *Incidentally, are you using junior/senior to denote 5-hour/8-hour or to denote Scouts/Explorers?*
4. Okay, so if the target phone-in time is 21:10, then 21:10 &le; *t* &lt; 21:11 scores 30, 21:09 &le; *t* &lt; 21:10 and 21:11 &le; *t* &lt; 21:12 score 29, … , 22:41 &le; *t* &lt; 22:42 and 21:39 &le; *t* &lt; 21:40 score 1, and *t* &lt; 22:41 and *t* &ge; 21:40 score 0.
5.  
6.  
7.  Do you mean 29, 28, … rather than -1, -2, … ? So if target finish time is 23:40, then *t* &lt; 23:41 scores 30, 23:41 &le; *t* &lt; 23:42 scores 29, … , 00:09 &le; *t* &lt; 00:10 scores 1, and *t* &gt; 00:10 scores 0 (and disqualification).
8.

**Comment by danielswaine** [comment]
1. Where has 120 come from? Teams start with 60 (so 30 for the phone in which can be taken away and same for finish)
3. Hmm, Junior/Senior for 5/8hour
4. Correct (I think) - if target phone-in time is 21:10 and they meet this time the 30 points stand, if they phone in at 21:09 or 21:11 then will get 29 points etc...
7. Correct

**Comment by danielswaine** [comment]
1. Where has 120 come from? Teams start with 60 (so 30 for the phone in which can be taken away and same for finish)
3. Hmm, Junior/Senior for 5/8hour
4. Correct (I think) - if target phone-in time is 21:10 and they meet this time the 30 points stand, if they phone in at 21:09 or 21:11 then will get 29 points
7. Correct

**Comment by danielswaine** [comment]
1. Where has 120 come from? Teams start with 60 (so 30 for the phone in which can be taken away and same for finish)
2.
3. Hmm, Junior/Senior for 5/8hour
4. Correct (I think) - if target phone-in time is 21:10 and they meet this time the 30 points stand, if they phone in at 21:09 or 21:11 then will get 29 points
5.
6.
7. Correct

**Comment by joecridge** [comment]
The 120 is from starting with 60, receiving (up to) 30 for phoning in on time, and receiving (up to) 30 for finishing on time. I assumed that wasn't what you meant.

The rules state that the phone-in points are bonuses but the finish time points are deductions, so I think we should either have:
- All teams start with 0 points, with +30, +29, +28, etc points for phoning in on time, and 0, -1, -2, etc points for finish time; or
- As above, but with all teams starting with 30 points. That way no-one can get negative points.

**Comment by danielswaine** [comment]
They start with 60 but those 60 points are taken away if necessary (with late phone-in or finish)? Sorry if I'm not making sense.

**Comment by joecridge** [comment]
Nah I get it now :stuck_out_tongue_closed_eyes:. I'm gonna go with the second bullet point, it's numerically the same as what you've saying but semantically truer to the rules.

**Comment by danielswaine** [comment]
Option 2 but start with 60? :laughing:

**Comment by joecridge** [comment]
That will mean that everyone this year has a bonus 30 points compared to previous years…
