### ISSUE TITLE
Checkpoints index PDF

### ISSUE THREAD

**Issue by joecridge** [danielswaine/SodburyChallenge#3]
- Punch grid of *all* checkpoints chosen for the year (for all sections so only need to print one type of sheet)
- Organisers' master list for the year: all chosen checkpoints (number, section, grid ref, description, score for each section) and compulsory checkpoint(s)
- Team sheets for juniors/seniors (team number, team name; and space for actual start time, etc.)

**Comment by joecridge** [comment]
I've updated the server so that the Download as PDF button works to some extent (see #34).

The PDF is defined in `app/views/checkpoints/index.pdf.prawn`. At the moment it renders the first 20 checkpoints as provided by `will_paginate`. Can you try and work out how to access the checkpoints from the other pages and print them?

The list could benefit from some formatting as well, either by using a grid layout (see <http://prawnpdf.org/manual.pdf>) or by [prawn-table](https://github.com/prawnpdf/prawn-table).

**Comment by joecridge** [comment]
![screen shot 2015-10-03 at 02 10 42](https://cloud.githubusercontent.com/assets/11491479/10260712/00cb39b8-6974-11e5-9c93-258da574cfda.png)

**Comment by danielswaine** [comment]
So, I can get it to output page 1 OR page 2 depending on which page you're currently viewing, but not all in one list XD

**Comment by joecridge** [comment]
Just merged and #36 and deployed: [checkpoints.pdf](http://178.62.20.90/checkpoints.pdf).

**Comment by joecridge** [comment]
Re comment on #36:

I can't see anything wrong with your syntax but I haven't read the prawn-rails docs. Does it still throw an error if you comment our lines 34–36?

**Comment by danielswaine** [comment]
Not sure what the difference was, but got it working :+1:

**Comment by joecridge** [comment]
Awesome, does it display all 73 points?

**Comment by danielswaine** [comment]
I don't have all 73 checkpoints on localhost but here is what it looks like now:

![screen shot 2015-10-03 at 22 42 00](https://cloud.githubusercontent.com/assets/12982563/10265234/ff4f2a7a-6a1f-11e5-9119-248ba860a6cf.png)

Only thing is I can't work out table headers at the minute!

**Comment by joecridge** [comment]
Great, what I meant was does it display more than 20 or is it just the page you're looking at?

If it's only one page at a time, can you rebase against master and see if it displays all of them?

**Comment by danielswaine** [comment]
How do I do that? :worried:

**Comment by joecridge** [comment]
```
$ git checkout master
$ git pull origin master
$ git checkout prawn-dan
$ git rebase master
```

**Comment by joecridge** [comment]
Stash or commit any unstaged changes first though.

**Comment by danielswaine** [comment]
Thanks. Shows all of them on my localhost :+1:

**Comment by joecridge** [comment]
Yay :D

**Comment by danielswaine** [comment]
Now next question, how do I put to master?

**Comment by joecridge** [comment]
```
$ git push origin prawn-dan
```
then click *Compare and Pull Request* in the yellow box on the repo code page, merge, click to delete the merged branch on origin, then back on your machine:

```
$ git checkout master
$ git pull origin master
$ git branch -d prawn-dan
```

Can you try and add headers first though? You're not really supposed to commit changes to master that remove functionality :stuck_out_tongue_winking_eye:

**Comment by joecridge** [comment]
Closed via #38.

**Comment by danielswaine** [comment]
For reference:
![screen shot 2015-10-03 at 23 22 56](https://cloud.githubusercontent.com/assets/12982563/10265373/ba0e69b6-6a25-11e5-9255-b1435d3f1129.png)

**Comment by joecridge** [comment]
This is awesome :+1:

**Comment by joecridge** [comment]
I'm hoping that the table will just wrap the description.

**Comment by danielswaine** [comment]
Ah I see. Can I deploy, or is that for you to do?

**Comment by joecridge** [comment]
Go for it, process is [here](https://github.com/danielswaine/SodburyChallenge/wiki/Normal-Deploy).

**Comment by danielswaine** [comment]
Damn - it worked but for some reason the headers aren't there!

**Comment by joecridge** [comment]
You're PR says in the title that headers haven't been added. Did you definitely push all your commits up?

**Comment by joecridge** [comment]
Also could you make the grid reference column a bit smaller so that there's more hspace for the descriptions? :wink:

**Comment by danielswaine** [comment]
It's live now. Is that better Sir? :wink:

**Comment by joecridge** [comment]
One is happy now :P
